-- MySQL Script generated by MySQL Workbench
-- Wed Mar 10 08:39:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `login_Id` INT(11) NOT NULL AUTO_INCREMENT,
  `email_address` VARCHAR(255) NULL,
  `first_name` VARCHAR(25) NULL,
  `last_name` VARCHAR(25) NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  `type` VARCHAR(10) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`login_Id`));


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `client_Id` INT(11) NOT NULL AUTO_INCREMENT,
  `email_address` VARCHAR(255) NULL,
  `first_name` VARCHAR(25) NULL,
  `last_name` VARCHAR(25) NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  `country_code` INT(5) NULL,
  `mobile` INT(11) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `address` VARCHAR(200) NULL,
  `nick_name` VARCHAR(45) NULL,
  `type` ENUM('active', 'in-active', 'hold') NULL DEFAULT 'active',
  PRIMARY KEY (`client_Id`));


-- -----------------------------------------------------
-- Table `mydb`.`client_job_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`client_job_details` ;

CREATE TABLE IF NOT EXISTS `mydb`.`client_job_details` (
  `job_detail_id` INT(11) NOT NULL AUTO_INCREMENT,
  `client_id` INT(11) NULL,
  `project_details` LONGTEXT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`job_detail_id`),
  CONSTRAINT `client_id_fk`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`client_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `client_id_fk_idx` ON `mydb`.`client_job_details` (`client_id` ASC) ;


-- -----------------------------------------------------
-- Table `mydb`.`client_work_timing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`client_work_timing` ;

CREATE TABLE IF NOT EXISTS `mydb`.`client_work_timing` (
  `client_work_timing_id` INT(11) NOT NULL AUTO_INCREMENT,
  `client_id` INT(11) NULL,
  `end_time` VARCHAR(20) NOT NULL,
  `start_time` VARCHAR(20) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`client_work_timing_id`),
  CONSTRAINT `client_id_fk0`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`client_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `client_id_fk_idx` ON `mydb`.`client_work_timing` (`client_id` ASC) ;


-- -----------------------------------------------------
-- Table `mydb`.`master_rates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`master_rates` ;

CREATE TABLE IF NOT EXISTS `mydb`.`master_rates` (
  `master_rates_id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `amount` DOUBLE(10,2) NULL DEFAULT 0.0,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`master_rates_id`));


-- -----------------------------------------------------
-- Table `mydb`.`client_rates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`client_rates` ;

CREATE TABLE IF NOT EXISTS `mydb`.`client_rates` (
  `client_rates_id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `amount` DOUBLE(10,2) NULL DEFAULT 0.0,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `client_id` INT(11) NULL,
  PRIMARY KEY (`client_rates_id`)
 );

CREATE INDEX `client_id_fk_idx` ON `mydb`.`client_rates` (`client_id` ASC) ;

-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `employee_Id` INT(11) NOT NULL AUTO_INCREMENT,
  `email_address` VARCHAR(255) NULL,
  `first_name` VARCHAR(25) NULL,
  `last_name` VARCHAR(25) NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  `country_code` INT(5) NULL,
  `mobile` INT(11) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `address` VARCHAR(200) NULL,
  `nick_name` VARCHAR(45) NULL,
  `employee_type` ENUM('part-time', 'fulltime') NULL ,
  `status` TINYINT(1) NULL DEFAULT 1,
  `short_desc` VARCHAR(255) NULL,
  `key_tech_stack` VARCHAR(500) NULL,
  `auto_exp` VARCHAR(45) NULL,
  PRIMARY KEY (`employee_Id`));


-- -----------------------------------------------------
-- Table `mydb`.`employee_resume`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`employee_resume` ;

CREATE TABLE IF NOT EXISTS `mydb`.`employee_resume` (
  `emp_resume_id` INT(11) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `short_desc` VARCHAR(255) NULL,
  `data` LONGTEXT NULL,
  `file_location` VARCHAR(255) NULL,
  `employee_id` INT(11) NULL,
  PRIMARY KEY (`emp_resume_id`),
  CONSTRAINT `emp_id_fk`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`employee_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `emp_id_fk_idx` ON `mydb`.`employee_resume` (`employee_id` ASC) ;


-- -----------------------------------------------------
-- Table `mydb`.`time_sheet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`time_sheet` ;

CREATE TABLE IF NOT EXISTS `mydb`.`time_sheet` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `time_sheet_id` INT(11) NOT NULL AUTO_INCREMENT,
  `employee_id` INT(11) NULL,
  `client_id` INT(11) NULL,
  `no_of_hours` INT(11) NULL,
  `details_eod` VARCHAR(500) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`time_sheet_id`),
  CONSTRAINT `emp_id_timesheet_fk1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`employee_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `client_id_fk1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`client_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `emp_id_fk_idx` ON `mydb`.`time_sheet` (`employee_id` ASC) ;

CREATE INDEX `client_id_fk_idx` ON `mydb`.`time_sheet` (`client_id` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
